{
 "title": "PageSummary",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "category",
    "query": "SHOW TAG VALUES WITH KEY = \"category\""
   },
   {
    "name": "group",
    "label": "group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\" WHERE \"category\" =~ /$category/"
   },
   {
    "name": "page",
    "query": "SHOW TAG VALUES WITH KEY = \"page\" WHERE \"group\" =~ /$group/ AND \"category\" =~ /$category/"
   },
   {
    "name": "browser",
    "query": "SHOW TAG VALUES WITH KEY = \"browser\" WHERE \"group\" =~ /$group/ AND \"page\"  =~ /$page/ AND \"category\" =~ /$category/"
   },
   {
    "name": "connectivity",
    "query": "SHOW TAG VALUES WITH KEY = \"connectivity\" WHERE \"group\" =~ /$group/ AND \"page\"  =~ /$page/ AND \"browser\" =~ /$browser/ AND \"category\" =~ /$category/"
   }
  ]
 },
 "panels": [
  {
   "title": "First Visual Change",
   "type": "singlestat",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FirstVisualChange",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "singlestat",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SpeedIndex",
     "query": "SELECT last(\"median\") FROM \"SpeedIndex\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Visual Complete 85%",
   "type": "singlestat",
   "description": "The visual complete 85% is when 85% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VisualComplete85",
     "query": "SELECT last(\"median\") FROM \"VisualComplete85\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "singlestat",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LastVisualChange",
     "query": "SELECT last(\"median\") FROM \"LastVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "singlestat",
   "description": "Fully loaded time when the last of all assets is downloaded on the page. It is calculated using the Resource Timing API where we use the last downloaded asset.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullyLoaded",
     "query": "SELECT last(\"median\") FROM \"fullyLoaded\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT last(\"value\") FROM \"requests\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Transfer Size",
   "type": "singlestat",
   "description": "The total transfer size over the wire (compressed size if your asset is compressed) of all assets on the page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transferSize",
     "query": "SELECT last(\"value\") FROM \"transferSize\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'pagexray' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Content Size",
   "type": "singlestat",
   "description": "The total size for all assets served for this page. This includes the uncompressed size for compressed text/css/html/js/font content.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contentSize",
     "query": "SELECT last(\"value\") FROM \"contentSize\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'pagexray' AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Performance score",
   "type": "singlestat",
   "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "score",
     "query": "SELECT last(\"value\") FROM \"score\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"advice\" = 'performance' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "advice", "operator": "=", "value": "performance" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM Elements",
   "type": "singlestat",
   "description": "The total number of DOM elements on the page.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "domElements",
     "query": "SELECT last(\"value\") FROM \"domElements\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Document height",
   "type": "singlestat",
   "description": "The document height in pixels.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "documentHeight",
     "query": "SELECT last(\"value\") FROM \"documentHeight\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "IFrames",
   "type": "singlestat",
   "description": "The total number of iframes used on the page.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iframes",
     "query": "SELECT last(\"value\") FROM \"iframes\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM depth (avg)",
   "type": "singlestat",
   "description": "The average DOM depth of the page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "domDepth",
     "query": "SELECT last(\"value\") FROM \"iframes\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "DOM depth (max)",
   "type": "singlestat",
   "description": "The max depth of DOM elements on the page.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "domDepth",
     "query": "SELECT last(\"avg\") FROM \"domDepth\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Script tags",
   "type": "singlestat",
   "description": "Script tags in the DOM.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scripts",
     "query": "SELECT last(\"max\") FROM \"domDepth\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Domains",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "totalDomains",
     "query": "SELECT last(\"value\") FROM \"scripts\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'coach' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cookieStats",
     "query": "SELECT last(\"median\") FROM \"cookieStats\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'pagexray' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Local storage size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "localStorageSize",
     "query": "SELECT last(\"median\") FROM \"cookieStats\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"summaryType\" = 'pageSummary' AND \"origin\" = 'pagexray' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg last 24 hours",
   "type": "table",
   "description": "The moving average of the last 24 hours median values for the visual metrics.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "FirstVisualChange",
     "measurement": "FirstVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "LastVisualChange",
     "measurement": "LastVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "PerceptualSpeedIndex",
     "measurement": "PerceptualSpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "SpeedIndex",
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "VisualComplete85",
     "measurement": "VisualComplete85",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "FullyLoaded",
     "measurement": "fullyLoaded",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    }
   ]
  },
  {
   "title": "Relative to yesterday",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one day back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "alias": "FirstVisualChange",
     "measurement": "FirstVisualChange",
     "query": "SELECT moving_average(\"mean\", 10) FROM \"FirstVisualChange\" WHERE \"category\" =~ /^$category$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "LastVisualChange",
     "measurement": "LastVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "PerceptualSpeedIndex",
     "measurement": "PerceptualSpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "SpeedIndex",
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "VisualComplete85",
     "measurement": "VisualComplete85",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "FullyLoaded",
     "measurement": "fullyLoaded",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    }
   ]
  },
  {
   "title": "Relative to last week",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to seven days back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "FirstVisualChange",
     "measurement": "FirstVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "LastVisualChange",
     "measurement": "LastVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "PerceptualSpeedIndex",
     "measurement": "PerceptualSpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "SpeedIndex",
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "VisualComplete85",
     "measurement": "VisualComplete85",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "FullyLoaded",
     "measurement": "fullyLoaded",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    }
   ]
  },
  {
   "title": "Relative to last month",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one month back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "alias": "FirstVisualChange",
     "measurement": "FirstVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "LastVisualChange",
     "measurement": "LastVisualChange",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "PerceptualSpeedIndex",
     "measurement": "PerceptualSpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "SpeedIndex",
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "VisualComplete85",
     "measurement": "VisualComplete85",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    },
    {
     "alias": "FullyLoaded",
     "measurement": "fullyLoaded",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "40" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ],
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
    }
   ]
  },
  {
   "title": "First Visual Change",
   "type": "graph",
   "description": "The history of First Visual Change (when something for the first time is painted within the current viewport) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FirstVisualChange",
     "query": "SELECT median(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FirstVisualChange",
     "query": "SELECT median(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND $timeFilter AND  time > now() - 7d GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "FirstVisualChange",
     "query": "SELECT median(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "description": "The history of [Speed Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SpeedIndex",
     "query": "SELECT median(\"median\") FROM \"SpeedIndex\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "SpeedIndex",
     "query": "SELECT median(\"median\") FROM \"SpeedIndex\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "SpeedIndex",
     "query": "SELECT median(\"median\") FROM \"SpeedIndex\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Visual Complete 85%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VisualComplete85",
     "query": "SELECT median(\"median\") FROM \"VisualComplete85\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VisualComplete85",
     "query": "SELECT median(\"median\") FROM \"VisualComplete85\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "VisualComplete85",
     "query": "SELECT median(\"median\") FROM \"VisualComplete85\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LastVisualChange",
     "query": "SELECT median(\"median\") FROM \"LastVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastVisualChange",
     "query": "SELECT median(\"median\") FROM \"LastVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Monthly",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastVisualChange",
     "query": "SELECT median(\"median\") FROM \"LastVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullyLoaded",
     "query": "SELECT median(\"median\") FROM \"LastVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Weekly",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fullyLoaded",
     "query": "SELECT median(\"median\") FROM \"fullyLoaded\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    },
    {
     "alias": "Monthly",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fullyLoaded",
     "query": "SELECT median(\"median\") FROM \"fullyLoaded\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_contentType",
     "groupBy": [
      { "params": [ "contentType" ], "type": "tag" }
     ],
     "measurement": "contentSize",
     "query": "SELECT \"value\" FROM \"contentSize\" WHERE  \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"origin\" = 'pagexray' AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY \"contentType\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_contentType",
     "groupBy": [
      { "params": [ "contentType" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT \"value\" FROM \"requests\" WHERE  \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND \"origin\" = 'pagexray' AND \"category\" =~ /^$category$/ AND $timeFilter GROUP BY \"contentType\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" }
     ]
    }
   ]
  },
  {
   "title": "None 200 Response Codes",
   "type": "graph",
   "description": "All requests that are not a 200 HTTP Status Code.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Non 200",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" }
     ]
    }
   ]
  },
  {
   "title": "Time spent in backend vs frontend % [median]",
   "type": "graph",
   "description": "The max time spent in frontend vs backend time. \\n\\nThe backend time is the time it takes for the network and the server to generate and start sending the HTML. It is collected using the Navigation Timing API taking the responseStart minus navigationStart.\\n\\nThe frontend time is the time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Backend",
     "measurement": "backEndTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ]
    },
    {
     "alias": "Frontend",
     "measurement": "frontEndTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ]
    }
   ]
  },
  {
   "title": "DOMContentLoaded Time",
   "type": "graph",
   "description": "The time the browser takes to parse the document and execute deferred and parser-inserted scripts including the network time from the users location to your server.  It is collected using the Navigation Timing API by taking the domContentLoadedEventStart minus navigationStart.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "domContentLoadedTime",
     "query": "SELECT median(\"value\") FROM \"domContentLoadedTime\" WHERE \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"category\" =~ /^$category$/ AND $timeFilter AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "domContentLoadedTime",
     "query": "SELECT median(\"median\") FROM \"domContentLoadedTime\" WHERE \"browser\" =~ /^$browser$/ AND \"category\" =~ /^$category$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now() - 7d" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Time",
   "type": "graph",
   "description": "The time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frontEndTime",
     "query": "SELECT median(\"max\") FROM \"frontEndTime\" WHERE \"browser\" =~ /^$browser$/ AND \"category\" =~ /^$category$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "median",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frontEndTime",
     "query": "SELECT median(\"median\") FROM \"frontEndTime\" WHERE \"browser\" =~ /^$browser$/ AND \"category\" =~ /^$category$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "frontEndTime",
     "query": "SELECT median(\"min\") FROM \"frontEndTime\" WHERE \"browser\" =~ /^$browser$/ AND \"category\" =~ /^$category$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"group\" =~ /^$group$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "User Timings",
   "type": "graph",
   "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Now Current",
     "measurement": "domContentLoadedTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=", "value": "_" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ]
    },
    {
     "alias": "One Week Back Current",
     "measurement": "domContentLoadedTime",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=", "value": "_" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "graph",
   "description": "[Navigation Timing API](https://www.w3.org/TR/navigation-timing/) metrics.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "backendTime",
     "measurement": "backEndTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "backEndTime" }
     ]
    },
    {
     "alias": "domContentLoadedTime",
     "measurement": "domContentLoadedTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "domContentLoadedTime" }
     ]
    },
    {
     "alias": "domInteractiveTime",
     "measurement": "domInteractiveTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "domInteractiveTime" }
     ]
    },
    {
     "alias": "domainLookupTime",
     "measurement": "domainLookupTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "domainLookupTime" }
     ]
    },
    {
     "alias": "frontEndTime",
     "measurement": "frontEndTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "frontEndTime" }
     ]
    },
    {
     "alias": "pageDownloadTime",
     "measurement": "pageDownloadTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "pageDownloadTime" }
     ]
    },
    {
     "alias": "pageLoadTime",
     "measurement": "pageLoadTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "pageLoadTime" }
     ]
    },
    {
     "alias": "redirectionTime",
     "measurement": "redirectionTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "redirectionTime" }
     ]
    },
    {
     "alias": "serverConnectionTime",
     "measurement": "serverConnectionTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "serverConnectionTime" }
     ]
    },
    {
     "alias": "serverResponseTime",
     "measurement": "serverResponseTime",
     "select": [
      [
       { "params": [ "median" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "pageTimings", "operator": "=", "value": "serverResponseTime" }
     ]
    }
   ]
  },
  {
   "title": "Total CSS Content Size",
   "type": "singlestat",
   "description": "The total size for stylesheets assets served for this page. This includes the uncompressed size of CSS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "contentSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "css" }
     ]
    }
   ]
  },
  {
   "title": "Total CSS Transfert Size",
   "type": "singlestat",
   "description": "The total size over the wire for all stylesheet assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "transferSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "css" }
     ]
    }
   ]
  },
  {
   "title": "Total JS Content Size",
   "type": "singlestat",
   "description": "The total size for Javascripts assets served for this page. This includes the uncompressed size of JS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "contentSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" }
     ]
    }
   ]
  },
  {
   "title": "Total JS Transfer Size",
   "type": "singlestat",
   "description": "The total size over the wire for all Javascript assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "transferSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "javascript" }
     ]
    }
   ]
  },
  {
   "title": "Total HTML Content Size",
   "type": "singlestat",
   "description": "The total size for HTML served for this page. This includes the uncompressed size of HTML.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "contentSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "html" }
     ]
    }
   ]
  },
  {
   "title": "Total HTML Transfer Size",
   "type": "singlestat",
   "description": "The total size over the wire for all HTML served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 77 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "transferSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "html" }
     ]
    }
   ]
  },
  {
   "title": "Total Font Content Size",
   "type": "singlestat",
   "description": "The total size for font(s) served for this page. This includes the uncompressed size.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 80 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "contentSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "font" }
     ]
    }
   ]
  },
  {
   "title": "Total Font Transfer Size",
   "type": "singlestat",
   "description": "The total size over the wire for all font(s) served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 80 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "transferSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "font" }
     ]
    }
   ]
  },
  {
   "title": "Total Images Size",
   "type": "singlestat",
   "description": "The total size for images served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 80 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "contentSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "image" }
     ]
    }
   ]
  },
  {
   "title": "Total Other Transfer Size",
   "type": "singlestat",
   "description": "The total size for other elements served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 80 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "transferSize",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "contentType", "operator": "=", "value": "other" }
     ]
    }
   ]
  },
  {
   "title": "RUM Speed Index",
   "type": "singlestat",
   "description": "Calculate SpeedIndex measurements using Resource Timings",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 80 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "rumSpeedIndex",
     "query": "SELECT last(\"median\") FROM \"FirstVisualChange\" WHERE \"group\" =~ /^$group$/ AND \"browser\" =~ /^$browser$/ AND \"connectivity\" =~ /^$connectivity$/ AND \"page\" =~ /^$page$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
      { "condition": "AND", "key": "connectivity", "operator": "=~", "value": "/^$connectivity$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" }
     ]
    }
   ]
  }
 ]
}