{
 "title": "Server metrics monitoring",
 "description": "This dashboard provides various performance metrics for Linux systems, with templating to select the influxdb datasource and host.",
 "tags": [
  "server",
  "linux",
  "os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"uptime_value\" WITH KEY = \"host\""
   },
   { "name": "interval", "query": "10s,1m,5m,15m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Server Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"value\") FROM \"uptime_value\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "5min Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(value) FROM \"load_midterm\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value) FROM \"users_value\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(value) FROM \"memory_value\" WHERE \"type_instance\" = 'free' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "query": "SELECT last(value) FROM \"memory_value\" WHERE \"type_instance\" = 'used' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Buffered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value) FROM \"memory_value\" WHERE \"type_instance\" = 'buffered' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value) FROM \"memory_value\" WHERE \"type_instance\" = 'cached' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "(Stacked) Memory Distrubution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'used' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'free' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "buffered",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'buffered' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'cached' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "slab_recl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'slab_recl' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "slab_unrecl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"memory_value\" WHERE \"type_instance\" = 'slab_unrecl' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Data Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(value), 1s) FROM \"disk_read\" WHERE \"type\" = 'disk_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_instance Data Write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(value), 1s) FROM \"disk_write\" WHERE \"type\" = 'disk_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU $tag_instance $tag_type_instance",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "select derivative(mean(value),1s) AS idle from \"cpu_value\" WHERE \"type\" = 'cpu' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), instance, type_instance fill(null)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Data In",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(value), 1s)*8 FROM \"interface_rx\" WHERE \"type\"='if_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), instance fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_instance Data Out",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(value), 1s)*8 FROM \"interface_tx\" WHERE \"type\"='if_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), instance fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Errors In",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(value), 1s) FROM \"interface_rx\" WHERE \"type\"='if_errors' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), instance fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_instance Errors Out",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(value), 1s) FROM \"interface_tx\" WHERE \"type\"='if_errors' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), instance fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}