{
 "title": "WebPageTest site summary",
 "tags": [ "site" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "${VAR_BASE}" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "query": "$base.$path.summary.*" },
   {
    "name": "location",
    "query": "$base.$path.summary.$group.webpagetest.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.summary.$group.webpagetest.$location.*"
   },
   {
    "name": "view",
    "query": "$base.$path.summary.$group.webpagetest.$location.$connectivity.*.*"
   },
   { "name": "function", "query": "min, mean, median, max" }
  ]
 },
 "panels": [
  { "title": "$function", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.TTFB.$function"
    }
   ]
  },
  {
   "title": "Render",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.render.$function"
    }
   ]
  },
  {
   "title": "SpeedIndex",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.SpeedIndex.$function"
    }
   ]
  },
  {
   "title": "Fully loaded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.fullyLoaded.$function"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.requests.$function)"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.bytes.$function)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Start render",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.render.max, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.render.median, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.render.min, 10)"
    }
   ]
  },
  {
   "title": "SpeedIndex",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.SpeedIndex.max, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.SpeedIndex.median, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.SpeedIndex.min, 10)"
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.fullyLoaded.max, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.fullyLoaded.median, 10)"
    },
    {
     "target": "aliasByNode($base.$path.summary.$group.webpagetest.$location.$connectivity.timing.$view.fullyLoaded.min, 10)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.bytes.max), 12)"
    },
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.bytes.median), 12)"
    },
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.bytes.min), 12)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.requests.max), 12)"
    },
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.requests.median), 12)"
    },
    {
     "target": "aliasByNode(sumSeries($base.$path.summary.$group.webpagetest.$location.$connectivity.asset.$view.breakdown.*.requests.min), 12)"
    }
   ]
  }
 ]
}